Brian/graphql goodies
vendia/examples pull request #31
Opened 2022-03-08 13:25 UTC by brian-vendia

2022-03-08 14:00 UTC, james-vendia requested changes
Small changes requested for clarity.  Looks great.

2022-03-08 14:07 UTC, brian-vendia commented on features/share/graphql/creating-our-uni.md
> +* [Using Conditionals](./graphql-goodies/golang1.x/README.md)
Good call. I changed it to `graphql-enhancements`.

2022-03-09 14:47 UTC, ryansb commented on features/share/graphql/graphql-enhancements/python3/requirements.txt
> +gql
Instead of requiring `requests` and `requests_toolbelt` please use the gql install group `gql[requests]`

2022-03-09 14:47 UTC, ryansb commented on features/share/graphql/graphql-enhancements/node/README.md
> +```json
Can you format this JSON so it's easier to read?

2022-03-09 14:47 UTC, ryansb commented on features/share/graphql/graphql-enhancements/node/package-lock.json
> +{
I wouldn't include a package-lock.json for the demo, you already have requirements soft-pinned in package.json

2022-03-09 20:17 UTC, ryansb approved these changes

2022-03-09 20:18 UTC, merged